name: Deploy

on:
  push:
    branches:
      - alpha_live

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: yarn install

      - name: Build Nuxt
        run: yarn build

      - name: Generate Nuxt static files
        run: yarn generate
      
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://sebastianmorales.co --delete